# Generated by Django 5.0.2 on 2024-02-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_caption_user_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.ImageField(blank=True, null=True, upload_to='profileImage'),
        ),
    ]
