# Generated by Django 5.0.2 on 2024-02-13 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='user',
            name='post',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ImageField(blank=True, null=True, upload_to='profileImage')),
                ('caption', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
