# Generated by Django 5.0.2 on 2024-02-15 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ManyToManyField(related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
