# Generated by Django 5.0.2 on 2024-02-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
    ]
