# Generated by Django 5.0.2 on 2024-02-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
