# Generated by Django 5.0.2 on 2024-02-23 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='post.png', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.post'),
        ),
    ]
